project_id = "vlfleuwpsulnaamblfij"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-purchase-email]
verify_jwt = false

[functions.send-download-email]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.sync-purchase]
verify_jwt = false

[functions.log-activity]
verify_jwt = false

[functions.send-email]
verify_jwt = false
