import { CheckCircle, Rocket, Code2, Package } from "lucide-react";
import { RevealSection, RevealGrid } from "@/hooks/useScrollReveal";

const steps = [
  {
    icon: Package,
    step: "01",
    title: "Pick a Prototype",
    description: "Browse 40+ ready-made SaaS and mobile app prototypes. Project management, ATS, CRM, dashboards — it's all here.",
  },
  {
    icon: Code2,
    step: "02",
    title: "Download & Customize",
    description: "Get clean, well-structured source code. Swap colors, add your logo, tweak features. It's yours.",
  },
  {
    icon: Rocket,
    step: "03",
    title: "Ship It. Today.",
    description: "Deploy to Vercel, Netlify, or your own server. Go from idea to live product in a single afternoon.",
  },
];

export default function SolutionSection() {
  return (
    <section className="py-16 lg:py-20 section-alt">
      <RevealSection>
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold mb-4">
            <CheckCircle className="w-3.5 h-3.5" /> THE SOLUTION
          </div>
          <h2 className="font-poppins text-3xl md:text-4xl font-bold text-foreground mb-4">
            Skip the Build. <span className="gradient-text">Ship the Product.</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Production-ready prototypes built by real engineers. Not generated by AI.
            Not cobbled together from tutorials. Properly architected, tested, and ready to customize.
          </p>
        </div>
      </RevealSection>

      <RevealGrid className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto" stagger={120}>
        {steps.map(({ icon: Icon, step, title, description }, i) => (
          <div key={i} className="reveal-item glass-card p-7 text-center relative overflow-hidden">
            <div className="absolute top-3 right-4 text-5xl font-poppins font-extrabold text-primary/5">{step}</div>
            <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
              <Icon className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-poppins font-bold text-foreground mb-2 text-lg">{title}</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">{description}</p>
          </div>
        ))}
      </RevealGrid>
    </section>
  );
}
