import { z } from "zod";

export const env = z.object({
  APP_URL: z.string().default("http://localhost:3000"),
  API_URL: z.string().default("http://localhost:4000"),
  DATABASE_URL: z.string(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_PRICE_ID_PRO: z.string().optional(),
  STRIPE_PORTAL_RETURN_URL: z.string().default("http://localhost:3000/billing"),
  RAZORPAY_KEY_ID: z.string().optional(),
  RAZORPAY_KEY_SECRET: z.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GITHUB_CLIENT_ID: z.string().optional(),
  GITHUB_CLIENT_SECRET: z.string().optional(),
  LINKEDIN_CLIENT_ID: z.string().optional(),
  LINKEDIN_CLIENT_SECRET: z.string().optional(),
  EMAIL_PROVIDER: z.string().default("resend"),
  RESEND_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().default("noreply@example.com"),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_MESSAGING_SERVICE_SID: z.string().optional(),
  TWILIO_WHATSAPP_FROM: z.string().optional(),
  SOCIAL_PUBLISHER_ACCESS_TOKEN: z.string().optional(),
  N8N_BASE_URL: z.string().optional(),
  N8N_API_KEY: z.string().optional(),
  N8N_WEBHOOK_PATH: z.string().default("/webhook/velocitycore"),
  ZAPIER_WEBHOOK_URL: z.string().optional(),
  ZAPIER_SIGNING_SECRET: z.string().optional()
}).parse(process.env);
